# Generated by Django 4.1.3 on 2022-11-03 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Item',
        ),
    ]
