# Generated by Django 4.1.3 on 2022-11-12 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_alter_item_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creator",
            name="image",
            field=models.ImageField(upload_to="creator"),
        ),
    ]
